"use client";

import { FormEvent, PointerEvent, useEffect, useMemo, useRef, useState } from "react";

type Row = Record<string, unknown>;
type Data = { customers: Row[]; appointments: Row[]; services: Row[]; links: Row[]; settings: Record<string, string> };

const serviceTypes = ["霧眉", "霧唇", "補色", "其他"];
const notices = [
  "本人了解臉部骨骼、肌肉、皮膚狀態及曾接受醫美療程（如填充物、雷射、肉毒等），可能影響紋繡設計、位置判斷及術後呈現效果。",
  "本人了解紋繡效果會因個人體質、皮膚狀況、生活習慣及術後照護方式而有所差異，無法保證每位顧客呈現完全相同之效果。",
  "我已充分認知，在紋繡過程中可能引起疼痛及造成發炎風險的現象，並同意進行紋繡服務。",
  "我接受的半永久化妝紋繡，並非永久性上色，會因時間的關係而逐漸退色淡化及每個人膚質不同，留色會有些許不同，且需適當修復調整才會有較佳之效果。",
  "若想清除已完成的紋繡項目，需透過外科醫療程序來移除，任何其他有效的移除動作皆可能造成傷口或疤痕，需自行負責。",
  "補色為依個人留色情況進行調整之服務，實際補色時間需依皮膚恢復狀況評估。因個人體質差異，無法保證每次皆達到相同留色效果。",
];
const healthDisclosures = ["我必須將我所有醫美及醫療紀錄告知美容師，例如：臉部整形手術、長期服用止痛藥、阿斯匹靈。", "我沒有濫用藥物、酗酒等習慣", "我沒有懷孕", "我對藥物、食物、化妝品或相關產品沒有嚴重過敏反應", "其他"];
const conditions = ["疤痕皮膚炎／溼疹", "紋身", "蟹足腫", "血友病", "心臟病", "癲癇", "糖尿病", "血液不易凝固", "肝炎／黃疸病", "帶狀皰疹／皮蛇", "近期身體不適或發燒", "以上皆非"];
const lips = ["唇皰疹／口角炎（包括 60 天內曾經罹患）", "口腔潰瘍", "以上皆非", "其他"];
const photoOptions = ["僅作為本人術前術後紀錄保存", "同意遮蔽部分臉部後公開作品展示", "同意完整作品公開展示", "不同意任何公開使用"];
const confirmationItems = ["我已閱讀並了解紋繡術後保養須知及相關注意事項，並同意依照服務人員提供之術後照護方式進行保養。", "本人確認以上資料皆由本人詳實填寫，若有任何健康狀況或特殊情形，應於施作前主動告知服務人員。"];

const value = (row: Row | undefined, key: string) => String(row?.[key] ?? "");
const localDay = () => new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Taipei" });
const dateKey = (source: string) => source ? source.slice(0, 10) : "";
const showTime = (source: string) => source ? new Date(source).toLocaleString("zh-TW", { hour12: false }) : "—";
const changeList = (list: string[], item: string) => list.includes(item) ? list.filter((value) => value !== item) : [...list, item];
const customerName = (data: Data, id: string) => value(data.customers.find((item) => value(item, "id") === id), "full_name") || "未命名客戶";
const monthLabel = (month: string) => new Date(month + "-01T12:00:00").toLocaleDateString("zh-TW", { year: "numeric", month: "long" });

async function post(action: string, payload: Row = {}) {
  const response = await fetch("/api/studio", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, ...payload }) });
  const result = await response.json() as Row;
  if (!response.ok) throw new Error(value(result, "error") || "儲存失敗。");
  return result;
}

function SignaturePad({ onChange }: { onChange: (value: string) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null);
  const drawing = useRef(false);
  const [hasInk, setHasInk] = useState(false);
  useEffect(() => {
    const element = canvas.current, context = element?.getContext("2d");
    if (!element || !context) return;
    const ratio = window.devicePixelRatio || 1;
    element.width = element.clientWidth * ratio; element.height = element.clientHeight * ratio;
    context.scale(ratio, ratio); context.lineWidth = 2.2; context.lineCap = "round"; context.lineJoin = "round";
  }, []);
  const point = (event: PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
  const clear = () => { const element = canvas.current, context = element?.getContext("2d"); if (element && context) context.clearRect(0, 0, element.width, element.height); setHasInk(false); onChange(""); };
  return <div className="signature"><canvas ref={canvas} aria-label="手寫簽名欄" onPointerDown={(event) => { const context = canvas.current?.getContext("2d"); if (!context) return; drawing.current = true; event.currentTarget.setPointerCapture(event.pointerId); const p = point(event); context.beginPath(); context.moveTo(p.x, p.y); }} onPointerMove={(event) => { if (!drawing.current) return; const element = canvas.current, context = element?.getContext("2d"); if (!element || !context) return; const p = point(event); context.lineTo(p.x, p.y); context.stroke(); setHasInk(true); onChange(element.toDataURL("image/png")); }} onPointerUp={() => { drawing.current = false; }} /><div><span>{hasInk ? "已完成簽名" : "請在上方手寫簽名"}</span><button type="button" onClick={clear}>清除簽名</button></div></div>;
}

function CheckGroup({ title, items, selected, update, required = false }: { title: string; items: string[]; selected: string[]; update: (items: string[]) => void; required?: boolean }) {
  return <section className="contract-block"><h2>{title}{required && <em>＊</em>}</h2>{items.map((item) => <label className="big-check" key={item}><input type="checkbox" checked={selected.includes(item)} onChange={() => update(changeList(selected, item))} /><span>{item}</span></label>)}</section>;
}

function Intake({ token, home }: { token: string; home: () => void }) {
  const [ready, setReady] = useState(false), [error, setError] = useState(""), [signature, setSignature] = useState(""), [message, setMessage] = useState("");
  const [noticeChecks, setNoticeChecks] = useState<string[]>([]), [disclosureChecks, setDisclosureChecks] = useState<string[]>([]), [conditionChecks, setConditionChecks] = useState<string[]>([]), [lipChecks, setLipChecks] = useState<string[]>([]), [confirmationChecks, setConfirmationChecks] = useState<string[]>([]), [photo, setPhoto] = useState("");
  useEffect(() => { void fetch("/api/intake/" + token).then(async (response) => { const result = await response.json() as Row; if (!response.ok || !result.active) setError(value(result, "reason") || "此表單無法使用。"); else setReady(true); }).catch(() => setError("無法讀取表單。")); }, [token]);
  if (error) return <div className="public-shell"><section className="public-card compact"><h1>此連結無法使用</h1><p className="muted">{error}</p><button className="button secondary" onClick={home}>回首頁</button></section></div>;
  if (!ready) return <div className="public-shell"><section className="public-card compact">正在讀取表單…</section></div>;
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!signature) { setMessage("請完成手寫簽名。"); return; }
    const form = new FormData(event.currentTarget);
    try {
      const response = await fetch("/api/intake/" + token, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ fullName: form.get("fullName"), phone: form.get("phone"), lineId: form.get("lineId"), birthday: form.get("birthday"), referralSource: form.get("referralSource"), marketingConsent: Boolean(form.get("marketing")), reminderConsent: Boolean(form.get("reminder")), notices: noticeChecks, healthDisclosures: disclosureChecks, healthConditions: conditionChecks, lipConditions: lipChecks, photoAuthorization: photo, confirmations: confirmationChecks, signature }) });
      const result = await response.json() as Row; if (!response.ok) throw new Error(value(result, "error")); setMessage("已送出並保存，謝謝您。此連結現在已失效。");
    } catch (reason) { setMessage(reason instanceof Error ? reason.message : "送出失敗，請稍後重試。"); }
  };
  return <div className="public-shell"><section className="public-card"><p className="eyebrow">LULU STUDIO 紋繡美學</p><h1>服務知情同意書</h1><p className="muted">請依自身服務項目與健康狀況完成所有合約內容。</p><form onSubmit={submit}>
    <section className="contract-block contract-notice"><div className="contract-heading">服務須知與注意事項</div><p>請仔細閱讀以下注意事項，確認內容無誤並了解後，請勾選「✓」表示同意 <em>＊</em></p>{notices.map((item) => <label className="big-check" key={item}><input type="checkbox" checked={noticeChecks.includes(item)} onChange={() => setNoticeChecks(changeList(noticeChecks, item))} /><span>{item}</span></label>)}</section>
    <CheckGroup title="為保障您的安全與服務品質，請確認是否有以下健康狀況或特殊情形。" items={healthDisclosures} selected={disclosureChecks} update={setDisclosureChecks} />
    <CheckGroup title="若有以下健康狀況，請於施作前主動告知服務人員。" items={conditions} selected={conditionChecks} update={setConditionChecks} />
    <CheckGroup title="霧唇施作者專屬確認事項" items={lips} selected={lipChecks} update={setLipChecks} />
    <section className="contract-block"><h2>照片使用授權 <em>＊</em></h2>{photoOptions.map((item) => <label className="big-check radio" key={item}><input type="radio" name="photo" required checked={photo === item} onChange={() => setPhoto(item)} /><span>{item}</span></label>)}</section>
    <CheckGroup title="紋繡服務確認事項" items={confirmationItems} selected={confirmationChecks} update={setConfirmationChecks} required />
    <div className="form-grid"><label>姓名<input name="fullName" required /></label><label>電話<input name="phone" required inputMode="tel" /></label><label>LINE ID<input name="lineId" /></label><label>生日<input name="birthday" type="date" required /></label><label>得知管道<select name="referralSource" required defaultValue=""><option value="" disabled>請選擇</option><option>Facebook</option><option>Instagram</option><option>親友介紹</option><option>Google 搜尋</option></select></label></div>
    <label className="check"><input name="marketing" type="checkbox" />我同意於生日收到 Lulu Studio 優惠資訊。</label><label className="check"><input name="reminder" type="checkbox" />我同意收到下次服務或保養關心提醒。</label><h2>手寫簽名 <em>＊</em></h2><SignaturePad onChange={setSignature} />{message && <p className={message.startsWith("已送出") ? "notice success" : "notice error"}>{message}</p>}{!message.startsWith("已送出") && <button className="button primary">確認並送出表單</button>}
  </form></section></div>;
}

function CustomerPanel({ data, refresh, say }: { data: Data; refresh: () => Promise<void>; say: (message: string) => void }) {
  const [query, setQuery] = useState(""), [selectedId, setSelectedId] = useState(""), [newOpen, setNewOpen] = useState(false), [editOpen, setEditOpen] = useState(false), [serviceOpen, setServiceOpen] = useState(false), [expanded, setExpanded] = useState("");
  const selected = data.customers.find((item) => value(item, "id") === (selectedId || value(data.customers[0], "id")));
  const clients = useMemo(() => { const keyword = query.toLowerCase(); return data.customers.filter((item) => !keyword || ["full_name", "phone", "birthday", "line_id"].some((field) => value(item, field).toLowerCase().includes(keyword))); }, [data.customers, query]);
  const run = async (action: string, payload: Row) => { try { await post(action, payload); say("已保存。"); await refresh(); } catch (reason) { say(reason instanceof Error ? reason.message : "儲存失敗。"); } };
  const customerId = value(selected, "id");
  const customerServices = data.services.filter((item) => value(item, "customer_id") === customerId);
  return <div className="manager-grid"><section className="panel client-panel"><div className="section-title"><h2>客戶庫</h2><button className="button secondary small" onClick={() => setNewOpen(!newOpen)}>{newOpen ? "收合新增客戶" : "新增客戶"}</button></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋姓名、電話、生日、LINE ID" />
    {newOpen && <form className="soft-form inset" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await run("createCustomer", { fullName: form.get("fullName"), phone: form.get("phone"), lineId: form.get("lineId"), birthday: form.get("birthday"), referralSource: form.get("referralSource"), note: form.get("note") }); event.currentTarget.reset(); setNewOpen(false); }}><label>姓名<input required name="fullName" /></label><label>電話<input required name="phone" /></label><label>LINE ID<input name="lineId" /></label><label>生日<input required type="date" name="birthday" /></label><label>得知管道<select name="referralSource"><option>Facebook</option><option>Instagram</option><option>親友介紹</option><option>Google 搜尋</option></select></label><label>備註<textarea name="note" /></label><button className="button primary">保存新增客戶</button></form>}
    <div className="client-list">{clients.map((item) => <button className={value(item, "id") === customerId ? "selected" : ""} key={value(item, "id")} onClick={() => { setSelectedId(value(item, "id")); setEditOpen(false); }}><strong>{value(item, "full_name")}</strong><span>{value(item, "phone")} · {value(item, "line_id") || "未填 LINE ID"}</span></button>)}</div>
  </section><div className="details-stack">{selected && !editOpen && <section className="panel"><div className="section-title"><div><p className="eyebrow">CLIENT PROFILE</p><h2>客戶基本資料</h2></div><button className="button secondary small" onClick={() => setEditOpen(true)}>編輯</button></div><dl className="profile-grid"><div><dt>姓名</dt><dd>{value(selected, "full_name")}</dd></div><div><dt>電話</dt><dd>{value(selected, "phone")}</dd></div><div><dt>LINE ID</dt><dd>{value(selected, "line_id") || "—"}</dd></div><div><dt>生日</dt><dd>{value(selected, "birthday")}</dd></div><div><dt>得知管道</dt><dd>{value(selected, "referral_source") || "—"}</dd></div><div><dt>備註</dt><dd>{value(selected, "note") || "—"}</dd></div></dl></section>}
    {selected && <section className="panel"><div className="section-title"><h2>服務紀錄</h2><button className="button secondary small" onClick={() => setServiceOpen(!serviceOpen)}>{serviceOpen ? "收合新增服務紀錄" : "新增服務紀錄"}</button></div><div className="service-list">{customerServices.map((item) => <article className="service-item" key={value(item, "id")}><button className="service-summary" onClick={() => setExpanded(expanded === value(item, "id") ? "" : value(item, "id"))}><span>{showTime(value(item, "service_at"))} - {value(item, "service_type")}</span><span>{expanded === value(item, "id") ? "收合" : "展開"}</span></button>{expanded === value(item, "id") && <form className="service-detail" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await run("saveService", { id: value(item, "id"), customerId, serviceType: form.get("serviceType"), serviceAt: form.get("serviceAt"), careAt: form.get("careAt"), note: form.get("note") }); }}><label>服務<select name="serviceType" defaultValue={value(item, "service_type")}>{serviceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>服務時間<input name="serviceAt" required type="datetime-local" defaultValue={value(item, "service_at").slice(0, 16)} /></label><label>保養關心日<input name="careAt" type="date" defaultValue={value(item, "care_at")} /></label><label>服務紀錄<textarea name="note" required defaultValue={value(item, "note")} /></label><button className="button secondary small">保存修改</button></form>}</article>)}{!customerServices.length && <p className="muted">尚無服務紀錄。</p>}</div>
      {serviceOpen && <form className="soft-form inset" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await run("saveService", { customerId, serviceType: form.get("serviceType"), serviceAt: form.get("serviceAt"), careAt: form.get("careAt"), note: form.get("note") }); event.currentTarget.reset(); setServiceOpen(false); }}><label>服務<select name="serviceType">{serviceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>服務時間<input name="serviceAt" required type="datetime-local" /></label><label>保養關心日<input name="careAt" type="date" /></label><label>服務紀錄<textarea name="note" required /></label><button className="button primary">保存服務紀錄</button></form>}
    </section>}</div>
    {editOpen && selected && <form className="panel customer-edit-inline" key={customerId} onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await run("updateCustomer", { id: customerId, fullName: form.get("fullName"), phone: form.get("phone"), lineId: form.get("lineId"), birthday: form.get("birthday"), referralSource: form.get("referralSource"), note: form.get("note"), marketingConsent: Boolean(form.get("marketingConsent")), reminderConsent: Boolean(form.get("reminderConsent")) }); setEditOpen(false); }}><div className="section-title"><h2>編輯客戶資料</h2><button type="button" className="text-button" onClick={() => setEditOpen(false)}>關閉</button></div><div className="form-grid"><label>姓名<input required name="fullName" defaultValue={value(selected, "full_name")} /></label><label>電話<input required name="phone" defaultValue={value(selected, "phone")} /></label><label>LINE ID<input name="lineId" defaultValue={value(selected, "line_id")} /></label><label>生日<input required name="birthday" type="date" defaultValue={value(selected, "birthday")} /></label><label>得知管道<select name="referralSource" defaultValue={value(selected, "referral_source")}><option>Facebook</option><option>Instagram</option><option>親友介紹</option><option>Google 搜尋</option></select></label></div><label>備註<textarea name="note" defaultValue={value(selected, "note")} /></label><label className="check"><input name="marketingConsent" type="checkbox" defaultChecked={Boolean(selected.marketing_consent)} />生日優惠資訊</label><label className="check"><input name="reminderConsent" type="checkbox" defaultChecked={Boolean(selected.reminder_consent)} />保養／下次服務提醒</label><button className="button primary">保存客戶資料</button></form>}
  </div>;
}

function Calendar({ data, refresh, say }: { data: Data; refresh: () => Promise<void>; say: (message: string) => void }) {
  const today = localDay(), [month, setMonth] = useState(today.slice(0, 7)), [selectedDate, setSelectedDate] = useState(today), [newOpen, setNewOpen] = useState(false);
  const [year, monthIndex] = month.split("-").map(Number); const first = new Date(year, monthIndex - 1, 1).getDay(); const total = new Date(year, monthIndex, 0).getDate();
  const dates = Array.from({ length: first + total }, (_, index) => index < first ? "" : month + "-" + String(index - first + 1).padStart(2, "0"));
  const appointments = data.appointments.filter((item) => dateKey(value(item, "starts_at")) === selectedDate && value(item, "status") !== "cancelled");
  const care = data.services.filter((item) => value(item, "care_at") === selectedDate);
  const shift = (delta: number) => { const start = new Date(month + "-01T12:00:00"); start.setMonth(start.getMonth() + delta); const next = start.getFullYear() + "-" + String(start.getMonth() + 1).padStart(2, "0"); setMonth(next); setSelectedDate(next + "-01"); setNewOpen(false); };
  const saveAppointment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await post("saveAppointment", { customerId: form.get("customerId"), serviceType: form.get("serviceType"), startsAt: form.get("startsAt"), durationMinutes: form.get("durationMinutes"), status: "scheduled", note: form.get("note") }); say("預約已保存。"); await refresh(); setNewOpen(false); } catch (reason) { say(reason instanceof Error ? reason.message : "儲存失敗。"); } };
  return <div className="calendar-layout"><section className="panel"><div className="calendar-head"><button className="button secondary small" onClick={() => shift(-1)}>上個月</button><label>選擇年月<input type="month" value={month} onChange={(event) => { setMonth(event.target.value); setSelectedDate(event.target.value + "-01"); }} /></label><button className="button secondary small" onClick={() => shift(1)}>下個月</button></div><h2>{monthLabel(month)}</h2><div className="calendar-week">{["日", "一", "二", "三", "四", "五", "六"].map((label) => <span key={label}>{label}</span>)}</div><div className="month-grid">{dates.map((date, index) => date ? <button key={date} className={date === selectedDate ? "day-cell selected-day" : "day-cell"} onClick={() => { setSelectedDate(date); setNewOpen(false); }}><b>{Number(date.slice(8))}</b><span className="event-marks">{data.appointments.some((item) => dateKey(value(item, "starts_at")) === date && value(item, "status") !== "cancelled") && <i className="appointment-mark" title="有預約" />}{data.services.some((item) => value(item, "care_at") === date) && <i className="care-mark" title="保養關心" />}</span></button> : <span className="day-cell blank" key={index} />)}</div></section><section className="panel"><p className="eyebrow">DAILY TODO</p><div className="section-title"><h2>{selectedDate} 待辦</h2><button className="button secondary small" onClick={() => setNewOpen(!newOpen)}>{newOpen ? "收合新增預約" : "新增預約"}</button></div><h3>預約</h3>{appointments.map((item) => <p className="todo" key={value(item, "id")}>{customerName(data, value(item, "customer_id"))} · {value(item, "service_type")} · {showTime(value(item, "starts_at"))}</p>)}{!appointments.length && <p className="muted">本日尚無預約。</p>}<h3>保養關心</h3>{care.map((item) => <p className="todo" key={value(item, "id")}>{customerName(data, value(item, "customer_id"))} · {value(item, "service_type")}<small>服務時間：{showTime(value(item, "service_at"))}</small></p>)}{!care.length && <p className="muted">本日尚無保養關心。</p>}
  {newOpen && <form className="soft-form inset" onSubmit={saveAppointment}><label>客戶<select required name="customerId">{data.customers.map((item) => <option key={value(item, "id")} value={value(item, "id")}>{value(item, "full_name")}</option>)}</select></label><label>服務<select name="serviceType">{serviceTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>預約時間<input required name="startsAt" type="datetime-local" defaultValue={selectedDate + "T10:00"} /></label><label>時長（分鐘）<input name="durationMinutes" type="number" min="30" step="30" defaultValue="120" /></label><label>備註<textarea name="note" /></label><button className="button primary">保存預約</button></form>}
  </section></div>;
}

function Links({ data, refresh, say }: { data: Data; refresh: () => Promise<void>; say: (message: string) => void }) {
  const [created, setCreated] = useState("");
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await post("createFormLink", { days: form.get("days") }); setCreated(location.origin + "/?form=" + value(result.link as Row, "token")); say("已建立一次性表單連結。"); await refresh(); } catch (reason) { say(reason instanceof Error ? reason.message : "建立失敗。"); } };
  const revoke = async (id: string) => { try { await post("revokeFormLink", { id }); say("連結已撤銷。"); await refresh(); } catch (reason) { say(reason instanceof Error ? reason.message : "撤銷失敗。"); } };
  return <div className="two-column"><section className="panel"><p className="eyebrow">ONE-TIME INTAKE</p><h2>產生一次性網址</h2><p className="muted">每份表單皆提供完整合約內容；送出後立即作廢。</p><form className="soft-form" onSubmit={create}><label>有效天數<input name="days" type="number" min="1" max="30" defaultValue={data.settings.default_link_days || "1"} /></label><button className="button primary">產生連結</button></form>{created && <div className="link-card"><code>{created}</code><button className="button secondary" onClick={() => void navigator.clipboard.writeText(created)}>複製網址</button></div>}</section><section className="panel"><p className="eyebrow">RECENT LINKS</p><h2>連結紀錄</h2>{data.links.map((item) => <div className="record" key={value(item, "id")}><strong>{value(item, "service_type") || "綜合表單"} · {value(item, "status") === "active" ? "有效" : value(item, "status") === "used" ? "已使用" : "已撤銷"}</strong><span>到期：{showTime(value(item, "expires_at"))}</span>{value(item, "status") === "active" && <button className="text-button" onClick={() => void revoke(value(item, "id"))}>撤銷連結</button>}</div>)}</section></div>;
}

function Owner({ home }: { home: () => void }) {
  const [data, setData] = useState<Data>({ customers: [], appointments: [], services: [], links: [], settings: {} }), [tab, setTab] = useState("clients"), [message, setMessage] = useState("");
  const refresh = async () => { const response = await fetch("/api/studio", { cache: "no-store" }); const result = await response.json() as Data & Row; if (!response.ok) throw new Error(value(result, "error")); setData(result); };
  useEffect(() => { void refresh().catch((reason) => setMessage(reason instanceof Error ? reason.message : "無法讀取資料。")); }, []);
  const exportCsv = () => { const columns = ["姓名", "電話", "LINE ID", "生日", "得知管道", "備註"]; const rows = data.customers.map((item) => [value(item, "full_name"), value(item, "phone"), value(item, "line_id"), value(item, "birthday"), value(item, "referral_source"), value(item, "note")].map((cell) => '"' + cell.replaceAll('"', '""') + '"').join(",")); const blob = new Blob([[columns.join(","), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "lulu-studio-clients.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <main className="workspace"><div className="heading"><div><p className="eyebrow">OWNER CONSOLE · DEMO MODE</p><h1>Lulu Studio 管理端</h1><p className="muted">客戶、預約、服務與保養關心皆會保存至資料庫。Demo 未設定登入保護，請勿輸入真實個資。</p></div><div className="heading-actions"><button className="button secondary" onClick={exportCsv}>匯出 CSV</button><button className="text-button" onClick={home}>登出</button></div></div><div className="stats"><div><span>客戶總數</span><strong>{data.customers.length}</strong></div><div><span>今日預約</span><strong>{data.appointments.filter((item) => dateKey(value(item, "starts_at")) === localDay()).length}</strong></div><div><span>待保養關心</span><strong>{data.services.filter((item) => value(item, "care_at") === localDay()).length}</strong></div></div><div className="tabs"><button className={tab === "clients" ? "active" : ""} onClick={() => setTab("clients")}>客戶庫與服務紀錄</button><button className={tab === "calendar" ? "active" : ""} onClick={() => setTab("calendar")}>行事曆與每日待辦</button><button className={tab === "links" ? "active" : ""} onClick={() => setTab("links")}>一次性同意書連結</button></div>{message && <p className={message.includes("失敗") || message.includes("無法") ? "notice error" : "notice success"}>{message}</p>}{tab === "clients" && <CustomerPanel data={data} refresh={refresh} say={setMessage} />}{tab === "calendar" && <Calendar data={data} refresh={refresh} say={setMessage} />}{tab === "links" && <Links data={data} refresh={refresh} say={setMessage} />}</main>;
}

function Developer({ home }: { home: () => void }) {
  const [settings, setSettings] = useState<Record<string, string>>({}), [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/studio").then((response) => response.json()).then((result: Data) => setSettings(result.settings)); }, []);
  return <main className="workspace"><div className="heading"><div><p className="eyebrow">DEVELOPER CONSOLE · DEMO MODE</p><h1>網站設定</h1><p className="muted">正式上線前必須加入帳號驗證與權限控管。</p></div><button className="text-button" onClick={home}>登出</button></div><form className="panel settings" key={settings.studio_name} onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await post("saveSettings", { studioName: form.get("studioName"), defaultLinkDays: form.get("defaultLinkDays") }); setMessage("設定已保存。"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "保存失敗。"); } }}><label>工作室名稱<input name="studioName" defaultValue={settings.studio_name || "Lulu Studio紋繡美學"} /></label><label>預設連結有效天數<input name="defaultLinkDays" type="number" min="1" max="30" defaultValue={settings.default_link_days || "1"} /></label><label>LINE 訊息通道<input readOnly value="預留：生日優惠與下次服務提醒（尚未串接 LINE Messaging API）" /></label><div className="notice">Demo 安全提醒：管理端目前沒有真實登入保護，任何可開啟網址的人都能查看資料。請只使用測試資料。</div>{message && <p className="notice success">{message}</p>}<button className="button primary">保存設定</button></form></main>;
}

export default function LuluDemo() {
  const token = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("form") || "";
  const [screen, setScreen] = useState<"home" | "login" | "owner" | "developer" | "public">(token ? "public" : "home");
  const home = () => { history.replaceState({}, "", "/"); setScreen("home"); };
  if (screen === "public") return <Intake token={token} home={home} />;
  if (screen === "owner") return <div className="app-shell"><header><button className="brand" onClick={home}>Lulu Studio紋繡美學<small>CLIENT CARE · DEMO</small></button><nav>經營者端</nav></header><Owner home={home} /></div>;
  if (screen === "developer") return <div className="app-shell"><header><button className="brand" onClick={home}>Lulu Studio紋繡美學<small>CLIENT CARE · DEMO</small></button><nav>開發者端</nav></header><Developer home={home} /></div>;
  if (screen === "login") return <div className="login-shell"><form className="login-card" onSubmit={(event) => { event.preventDefault(); const email = String(new FormData(event.currentTarget).get("email")); setScreen(email.toLowerCase().includes("dev") ? "developer" : "owner"); }}><p className="eyebrow">LULU STUDIO · DEMO ACCESS</p><h1>進入管理端</h1><p className="muted">此版依需求未啟用安全驗證。信箱含 dev 時進入開發者端，其餘進入經營者端。</p><label>電子信箱<input name="email" required type="email" placeholder="owner@lulu.demo 或 dev@lulu.demo" /></label><label>密碼<input name="password" required type="password" minLength={8} placeholder="任意 8 碼以上（Demo）" /></label><button className="button primary">進入 Demo</button><button className="text-button" type="button" onClick={home}>回首頁</button></form></div>;
  return <main className="landing-shell"><section className="landing-card"><p className="eyebrow">LULU STUDIO 紋繡美學</p><h1>把每一份信任<br />好好保存下來。</h1><p className="landing-copy">整合一次性同意書、客戶資料、預約行事曆、服務紀錄與保養關心的紋繡工作流程 Demo。</p><button className="button primary" onClick={() => setScreen("login")}>進入管理端</button><div className="landing-trust"><span>一次性表單</span><span>手寫簽名</span><span>資料庫保存</span><span>LINE 提醒預留</span></div></section><section className="how-grid"><article><b>01</b><h2>建立連結</h2><p>產生可直接傳送給客戶的完整同意書網址。</p></article><article><b>02</b><h2>客戶填寫</h2><p>合約、健康狀況、照片授權與簽名皆會保存。</p></article><article><b>03</b><h2>服務追蹤</h2><p>管理端可編輯客戶、安排預約、記錄服務並管理保養關心日。</p></article></section></main>;
}
