"use client";
import ConsentRecord from "./consent-record";
import { useEffect, useState } from "react";
import { value, type Row } from "./studio-panels";
export default function CustomerTools({customer,send,reload,say}:{customer:Row;send:(path:string,body:unknown)=>Promise<Row>;reload:()=>Promise<void>;say:(message:string)=>void}) {
  const [consents,setConsents]=useState<Row[]>([]), [document,setDocument]=useState<Row|null>(null);const customerId=value(customer,"id");
  useEffect(()=>{let cancelled=false;void fetch(`/api/admin/consents?customerId=${encodeURIComponent(customerId)}`,{cache:"no-store"}).then(async response=>{const result=await response.json() as Row;if(!response.ok)throw new Error(value(result,"error")||"無法讀取同意書");if(!cancelled)setConsents(result.consents as Row[]);}).catch(reason=>{if(!cancelled)say(reason instanceof Error?reason.message:"無法讀取同意書");});return()=>{cancelled=true;};},[customerId,say]);
  const change=async(action:string)=>{const confirmation=action==="delete"?window.prompt(`永久刪除「${value(customer,"full_name")}」及其服務、同意書、簽名與照片，請輸入「永久刪除」確認`):undefined;if(confirmation===null)return;try{await send("/api/admin/customers",{action,id:customerId,confirmation});await reload();say(action==="delete"?"客戶資料已永久刪除":action==="archive"?"客戶已封存":"客戶已恢復");}catch(reason){say(reason instanceof Error?reason.message:"操作失敗");}};
  const show=async(id:string)=>{try{const response=await fetch(`/api/admin/consents/${encodeURIComponent(id)}`,{cache:"no-store"});const result=await response.json() as Row;if(!response.ok)throw new Error(value(result,"error")||"無法讀取同意書");setDocument(result);}catch(reason){say(reason instanceof Error?reason.message:"無法讀取同意書");}};
  return <section className="panel"><h2>資料保存與同意書</h2>{Boolean(customer.archived_at)&&<p className="notice">此客戶已封存；新增預約或服務前請先恢復。</p>}<div className="form-actions"><button className="button secondary" onClick={()=>void change(customer.archived_at?"restore":"archive")}>{customer.archived_at?"恢復客戶":"封存客戶"}</button><button className="text-button" onClick={()=>void change("delete")}>永久刪除</button></div><h3>歷史同意書</h3>{consents.length?consents.map(item=><div className="record" key={value(item,"id")}><span>{value(item,"submitted_at")} · {value(item,"contract_version")}</span><button className="button secondary" onClick={()=>void show(value(item,"id"))}>調閱</button></div>):<p className="muted">尚無同意書紀錄。回訪同意書請由工作室人工處理。</p>}{document&&<article className="inset"><button className="text-button" onClick={()=>setDocument(null)}>關閉同意書</button><ConsentRecord document={document}/></article>}</section>;
}
