"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Calendar, CustomerPanel, Links, StudioActionsContext, dateKey, localDay, value, type Row, type StudioData, type StudioPost } from "./studio-panels";
import DeveloperPanel from "./production-developer";
import CustomerTools from "./production-customer-tools";
type Data = StudioData & { csrf:string; actor:{email:string;role:string}; formLinks:Row[] };
export default function ProductionAdmin({developer=false}:{developer?:boolean}) {
  const [data,setData]=useState<Data|null>(null), [tab,setTab]=useState("clients"), [message,setMessage]=useState(""), [error,setError]=useState("");
  const load=async()=>{const response=await fetch("/api/admin/bootstrap",{credentials:"same-origin",cache:"no-store"});const body=await response.json() as Data & {error?:string};if(response.status===401){window.location.assign("/login");return;}if(!response.ok)throw new Error(body.error||"無法讀取管理資料");setData({...body,links:body.formLinks});};
  useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"無法讀取資料"));},0);return()=>window.clearTimeout(timer);},[]);
  const send=async(path:string,body:unknown):Promise<Row>=>{if(!data)throw new Error("管理資料尚未載入");const response=await fetch(path,{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","x-csrf-token":data.csrf},body:JSON.stringify(body)});const result=await response.json() as Row;if(response.status===401)window.location.assign("/login");if(!response.ok)throw new Error(value(result,"error")||"儲存失敗");return result;};
  const post:StudioPost=(action,payload={})=>{switch(action){case "createCustomer":return send("/api/admin/customers",{...payload,action:"create"});case "updateCustomer":return send("/api/admin/customers",{...payload,action:"update"});case "saveAppointment":return send("/api/admin/appointments",payload);case "saveService":return send("/api/admin/services",payload);case "createFormLink":return send("/api/admin/form-links",payload);case "revokeFormLink":return send("/api/admin/form-links",{...payload,action:"revoke"});default:throw new Error("不支援的正式管理操作");}};
  if(!data)return <main className="public-shell"><section className="public-card"><h1>{error?"管理端尚未開放":"正在讀取管理資料…"}</h1>{error&&<p className="notice error" role="alert">{error}</p>}<Link href="/">回到首頁</Link></section></main>;
  const studio=data.settings.studio_name||"Lulu Studio紋繡美學";
  return <StudioActionsContext.Provider value={post}><main className="app-shell"><header><Link className="brand" href="/">{studio}<small>{developer?"DEVELOPER SETTINGS":"OWNER CONSOLE"}</small></Link><nav><span>{data.actor.email}</span>{data.actor.role==="developer"&&<a href={developer?"/admin":"/developer"}>{developer?"經營者端":"開發者設定"}</a>}<button onClick={()=>{void send("/api/auth/logout",{}).then(()=>window.location.assign("/login")).catch(reason=>setError(reason.message));}}>登出</button></nav></header><section className="workspace"><div className="heading"><div><p className="eyebrow">正式營運版</p><h1>{developer?"開發者設定":`${studio} 管理端`}</h1><p className="muted">客戶、預約、服務與保養關心；所有寫入均保存操作者與時間。</p></div>{!developer&&<a className="button secondary" href="/api/admin/export">下載一般客戶 CSV</a>}</div>{error&&<p className="notice error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
  {developer?(data.actor.role==="developer"?<DeveloperPanel data={data} send={send} reload={load} setMessage={setMessage} setError={setError}/>:<p className="notice error">此帳號沒有開發者權限。</p>):<><div className="stats"><div><span>啟用客戶</span><strong>{data.customers.filter(item=>!item.archived_at).length}</strong></div><div><span>今日預約</span><strong>{data.appointments.filter(item=>item.status!=="cancelled"&&dateKey(value(item,"starts_at"))===localDay()).length}</strong></div><div><span>待保養關心</span><strong>{data.services.filter(item=>item.care_at===localDay()).length}</strong></div></div><div className="tabs"><button className={tab==="clients"?"active":""} onClick={()=>setTab("clients")}>客戶庫與服務紀錄</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}>行事曆與每日待辦</button><button className={tab==="links"?"active":""} onClick={()=>setTab("links")}>一次性同意書連結</button></div>{tab==="clients"&&<CustomerPanel data={data} refresh={load} say={setMessage} renderCustomerActions={customer=><CustomerTools key={value(customer,"id")} customer={customer} send={send} reload={load} say={setMessage}/>}/>} {tab==="calendar"&&<Calendar data={{...data,customers:data.customers.filter(item=>!item.archived_at)}} refresh={load} say={setMessage}/>} {tab==="links"&&<Links data={data} refresh={load} say={setMessage}/>}</>}
  </section></main></StudioActionsContext.Provider>;
}
